name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Generate Keystore
      run: |
        keytool -genkey -v \
          -keystore bunker.keystore \
          -alias bunkerkey \
          -keyalg RSA -keysize 2048 \
          -validity 10000 \
          -storepass bunker123 \
          -keypass bunker123 \
          -dname "CN=Bunker, OU=Game, O=Bunker, L=City, S=State, C=RU"

    - name: Upload Keystore
      uses: actions/upload-artifact@v4
      with:
        name: bunker-keystore
        path: bunker.keystore
